FROM mcr.microsoft.com/playwright/python:v1.49.1-noble

RUN apt update
RUN apt install pipx -y
RUN pipx ensurepath
RUN pipx install poetry
ENV PATH="${PATH}:/root/.local/bin"

WORKDIR /app
RUN mkdir ./src
RUN mkdir ./logs
RUN mkdir ./data
RUN chmod -R a+rw ./data
COPY ./src ./src
COPY pyproject.toml ./
RUN poetry install --sync --with poller

CMD ["poetry", "run", "python", "src/creator_poller.py"]