FROM python:3.12-slim

RUN apt update
RUN apt install pipx -y
RUN pipx ensurepath
RUN pipx install poetry
ENV PATH="${PATH}:/root/.local/bin"

WORKDIR /app
RUN mkdir ./src
RUN mkdir ./logs
RUN mkdir ./data
RUN chmod -R a+rw ./data
COPY ./src ./src
COPY pyproject.toml ./
RUN poetry install --sync --with writer

CMD ["poetry", "run", "python", "src/writer.py"]